# jaringan luar
spring.datasource.url= jdbc:postgresql://cloudias79.com:5545/multitech_bookrecipe

# jaringan kantor
#spring.datasource.url= jdbc:postgresql://10.10.5.180:5432/multitech_bookrecipe 
spring.datasource.username= usrmultitech
spring.datasource.password= 4NGeHQ44y271

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto= validate

tujuhsembilan.app.jwtSecret= bookrecipe
tujuhsembilan.app.jwtExpirationMs= 86400000

minio.endpoint=https://minio.cloudias79.com/
minio.accessKey=talent79
minio.secretKey=evT25hDUUdf0gl1M9WOtwo3T3
minio.bucketName=talent79-dev