# --- KONFIGURASI DATABASE LOKAL ---
spring.datasource.url= jdbc:postgresql://localhost:5432/glucoseclamp
spring.datasource.username= postgres
spring.datasource.password= 1234567890
# (Silakan ubah username dan password di atas sesuai dengan setup PostgreSQL di komputermu)

# --- JARINGAN LUAR (Uncomment jika ingin pakai DB cloudias79) ---
# spring.datasource.url= jdbc:postgresql://cloudias79.com:5545/glucoseclamp
# spring.datasource.username= usrmultitech
# spring.datasource.password= 4NGeHQ44y271

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto= update

# --- PAGINATION ---
spring.data.web.pageable.one-indexed-parameters= true
spring.data.web.pageable.page-parameter= pageNumber
spring.data.web.pageable.size-parameter= pageSize
spring.data.web.sort.sort-parameter= sortBy

# --- JWT ---
tujuhsembilan.app.jwtSecret= my32characterultrasecureandultralongglucoseclamp
tujuhsembilan.app.jwtExpirationMs= 86400000

# --- SWAGGER ---
tujuhsembilan.openapi.local-url=http://localhost:8080/api
tujuhsembilan.openapi.dev-url=https://glucose-clamp-spring.apps.paas.spacex79.xyz/api
tujuhsembilan.openapi.module-name=Glucose Clamp API
tujuhsembilan.openapi.module-desc=This API exposes endpoints to manage Glucose Clamp for 79 Multi Tech Case Study
tujuhsembilan.openapi.api-version=v1.0

springdoc.swagger-ui.path=/glucoseclamp-documentation
springdoc.api-docs.path=/glucoseclamp-api-docs

# Pastikan package controller ini sesuai dengan nama package barumu
springdoc.packages-to-scan=com.tujuhsembilan.glucoseclamp.controller
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.filter=true

# --- I18N (Dibiarkan menyala) ---
spring.messages.encoding = UTF-8
spring.messages.basename = i18n/messages 

# --- PATH & DEBUGGING ---
server.servlet.context-path = /api

# Seeder toggle: ubah ke false kalau tidak ingin SeedDataRunner berjalan saat startup
app.seed.enabled=true

# logging.level.org.springframework.web=DEBUG
# spring.mvc.log-request-details=false

spring.jackson.serialization.write-dates-as-timestamps=false