package com.tujuhsembilan.bookrecipe.model;
// Generated Jan 4, 2024, 3:00:37 PM by Hibernate Tools 6.3.1.Final

import java.sql.Timestamp;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * FavoriteFoodsId generated by hbm2java
 */

@Data
@AllArgsConstructor
@NoArgsConstructor
@Embeddable
@EntityListeners(AuditingEntityListener.class)
public class FavoriteFoodsId implements java.io.Serializable {

	@Column(name = "Created_by")
	private String createdBy;

	@CreatedDate
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time", length = 29)
	private Timestamp createdTime;

	@Column(name = "is_favorite")
	private Boolean isFavorite;

	@Column(name = "modified_by")
	private String modifiedBy;

	@CreatedDate
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_time", length = 29)
	private Timestamp modifiedTime;

	@Column(name = "recipe_id")
	private Integer recipeId;

	@Column(name = "user_id")
	private Integer userId;
}
