package com.tujuhsembilan.bookrecipe.model;
// Generated Jan 4, 2024, 3:00:37 PM by Hibernate Tools 6.3.1.Final

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.MapsId;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * FavoriteFoods generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@EntityListeners(AuditingEntityListener.class)
public class FavoriteFoods implements java.io.Serializable {

	@EmbeddedId
	private FavoriteFoodsId id;

	@ManyToOne
    @MapsId("recipeId")
    @JoinColumn(name = "recipe_id")
	private Recipes recipes;

	@ManyToOne
    @MapsId("userId")
    @JoinColumn(name = "user_id")
	private Users users;

}
