DO $$ 
DECLARE
    v_need_migration boolean := false;
    v_rec record;
    v_max_id bigint;
BEGIN 
    -- 1. Nangtukeun naha migrasi tipe data ID diperyogikeun.
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = current_schema()
          AND table_name IN ('infusion_monitorings', 'blood_samples', 'lab_results') 
          AND column_name IN ('infusion_id', 'blood_sample_id', 'lab_result_id')
          AND data_type IN ('character varying', 'character', 'text')
    ) THEN
        v_need_migration := true;
    END IF;

    -- 2. Proses migrasi ID
    IF v_need_migration THEN
        
        -- A. HAPUS FOREIGN KEY CONSTRAINT (Dilereskeun ku JOIN skéma)
        FOR v_rec IN (
            SELECT tc.constraint_name, tc.table_schema, tc.table_name
            FROM information_schema.table_constraints tc 
            JOIN information_schema.key_column_usage kcu 
              ON tc.constraint_name = kcu.constraint_name 
              AND tc.table_schema = kcu.table_schema -- KEDAH JOIN SKÉMA OGÉ
            WHERE tc.table_schema = current_schema() 
              AND tc.table_name = 'lab_results' 
              AND tc.constraint_type = 'FOREIGN KEY'
              AND kcu.column_name = 'blood_sample_id'
        ) LOOP
            -- Ngagunakeun format %I supados aman tina identifier anu anéh
            EXECUTE format('ALTER TABLE %I.%I DROP CONSTRAINT %I', v_rec.table_schema, v_rec.table_name, v_rec.constraint_name);
        END LOOP;

        -- B. MIGRASI TABEL infusion_monitorings
        IF EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_schema = current_schema()
                     AND table_name='infusion_monitorings' AND column_name='infusion_id' 
                     AND data_type IN ('character varying', 'character', 'text')) THEN
                     
            ALTER TABLE infusion_monitorings 
                ALTER COLUMN infusion_id TYPE bigint 
                USING (regexp_replace(infusion_id, '[^0-9]', '', 'g')::bigint);

            ALTER TABLE infusion_monitorings 
                ALTER COLUMN infusion_id ADD GENERATED BY DEFAULT AS IDENTITY;

            SELECT COALESCE(MAX(infusion_id), 0) INTO v_max_id FROM infusion_monitorings;
            IF v_max_id > 0 THEN
                EXECUTE format('ALTER TABLE %I.infusion_monitorings ALTER COLUMN infusion_id RESTART WITH %s', current_schema(), v_max_id + 1);
            END IF;
        END IF;

        -- C. MIGRASI TABEL blood_samples
        IF EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_schema = current_schema()
                     AND table_name='blood_samples' AND column_name='blood_sample_id' 
                     AND data_type IN ('character varying', 'character', 'text')) THEN
                     
            ALTER TABLE blood_samples 
                ALTER COLUMN blood_sample_id TYPE bigint 
                USING (regexp_replace(blood_sample_id, '[^0-9]', '', 'g')::bigint);

            ALTER TABLE blood_samples 
                ALTER COLUMN blood_sample_id ADD GENERATED BY DEFAULT AS IDENTITY;

            SELECT COALESCE(MAX(blood_sample_id), 0) INTO v_max_id FROM blood_samples;
            IF v_max_id > 0 THEN
                EXECUTE format('ALTER TABLE %I.blood_samples ALTER COLUMN blood_sample_id RESTART WITH %s', current_schema(), v_max_id + 1);
            END IF;
        END IF;

        -- D. MIGRASI KOLOM FK blood_sample_id DI TABEL lab_results
        IF EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_schema = current_schema()
                     AND table_name='lab_results' AND column_name='blood_sample_id' 
                     AND data_type IN ('character varying', 'character', 'text')) THEN
                     
            ALTER TABLE lab_results 
                ALTER COLUMN blood_sample_id TYPE bigint 
                USING (regexp_replace(blood_sample_id, '[^0-9]', '', 'g')::bigint);
        END IF;

        -- E. MIGRASI TABEL lab_results (PRIMARY KEY)
        IF EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_schema = current_schema()
                     AND table_name='lab_results' AND column_name='lab_result_id' 
                     AND data_type IN ('character varying', 'character', 'text')) THEN
                     
            ALTER TABLE lab_results 
                ALTER COLUMN lab_result_id TYPE bigint 
                USING (regexp_replace(lab_result_id, '[^0-9]', '', 'g')::bigint);

            ALTER TABLE lab_results 
                ALTER COLUMN lab_result_id ADD GENERATED BY DEFAULT AS IDENTITY;

            SELECT COALESCE(MAX(lab_result_id), 0) INTO v_max_id FROM lab_results;
            IF v_max_id > 0 THEN
                EXECUTE format('ALTER TABLE %I.lab_results ALTER COLUMN lab_result_id RESTART WITH %s', current_schema(), v_max_id + 1);
            END IF;
        END IF;

        -- F. NYIEUN DEUI FOREIGN KEY CONSTRAINT
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.table_constraints 
            WHERE table_schema = current_schema() 
              AND constraint_name = 'fk_lab_results_blood_sample'
        ) THEN
            ALTER TABLE lab_results 
                ADD CONSTRAINT fk_lab_results_blood_sample 
                FOREIGN KEY (blood_sample_id) 
                REFERENCES blood_samples(blood_sample_id);
        END IF;

    END IF;

    -- 3. TAMBAH KOLOM minute DI TABEL activities
    IF EXISTS (
        SELECT 1 FROM information_schema.tables 
        WHERE table_schema = current_schema() 
          AND table_name = 'activities'
    ) THEN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns 
            WHERE table_schema = current_schema()
              AND table_name = 'activities' AND column_name = 'minute'
        ) THEN
            ALTER TABLE activities ADD COLUMN minute integer;
        END IF;
    END IF;

END $$;