DO $$ 
DECLARE
    v_need_migration boolean := false;
    v_rec record;
    v_max_id bigint;
BEGIN 
    -- 1. Tentukan apakah migrasi tipe data ID diperlukan.
    -- Kami memeriksa apakah salah satu dari ID utama ini masih berupa tipe karakter/string.
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name IN ('infusion_monitorings', 'blood_samples', 'lab_results') 
          AND column_name IN ('infusion_id', 'blood_sample_id', 'lab_result_id')
          AND data_type IN ('character varying', 'character', 'text')
    ) THEN
        v_need_migration := true;
    END IF;

    -- 2. Proses migrasi ID hanya berjalan jika kolom terdeteksi masih bertipe String/Varchar
    IF v_need_migration THEN
        
        -- A. HAPUS FOREIGN KEY CONSTRAINT SEBELUM MENGUBAH TIPE DATA
        -- Cari dan hapus semua FK di tabel lab_results yang merujuk ke blood_sample_id
        FOR v_rec IN (
            SELECT tc.constraint_name 
            FROM information_schema.table_constraints tc 
            JOIN information_schema.key_column_usage kcu 
              ON tc.constraint_name = kcu.constraint_name
            WHERE tc.table_name = 'lab_results' 
              AND tc.constraint_type = 'FOREIGN KEY'
              AND kcu.column_name = 'blood_sample_id'
        ) LOOP
            EXECUTE 'ALTER TABLE lab_results DROP CONSTRAINT ' || quote_ident(v_rec.constraint_name);
        END LOOP;

        -- B. MIGRASI TABEL infusion_monitorings
        IF EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name='infusion_monitorings' AND column_name='infusion_id' 
                     AND data_type IN ('character varying', 'character', 'text')) THEN
                     
            ALTER TABLE infusion_monitorings 
                ALTER COLUMN infusion_id TYPE bigint 
                USING (regexp_replace(infusion_id, '[^0-9]', '', 'g')::bigint);

            ALTER TABLE infusion_monitorings 
                ALTER COLUMN infusion_id ADD GENERATED BY DEFAULT AS IDENTITY;

            SELECT COALESCE(MAX(infusion_id), 0) INTO v_max_id FROM infusion_monitorings;
            IF v_max_id > 0 THEN
                EXECUTE 'ALTER TABLE infusion_monitorings ALTER COLUMN infusion_id RESTART WITH ' || (v_max_id + 1);
            END IF;
        END IF;

        -- C. MIGRASI TABEL blood_samples
        IF EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name='blood_samples' AND column_name='blood_sample_id' 
                     AND data_type IN ('character varying', 'character', 'text')) THEN
                     
            ALTER TABLE blood_samples 
                ALTER COLUMN blood_sample_id TYPE bigint 
                USING (regexp_replace(blood_sample_id, '[^0-9]', '', 'g')::bigint);

            ALTER TABLE blood_samples 
                ALTER COLUMN blood_sample_id ADD GENERATED BY DEFAULT AS IDENTITY;

            SELECT COALESCE(MAX(blood_sample_id), 0) INTO v_max_id FROM blood_samples;
            IF v_max_id > 0 THEN
                EXECUTE 'ALTER TABLE blood_samples ALTER COLUMN blood_sample_id RESTART WITH ' || (v_max_id + 1);
            END IF;
        END IF;

        -- D. MIGRASI KOLOM FK blood_sample_id DI TABEL lab_results
        IF EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name='lab_results' AND column_name='blood_sample_id' 
                     AND data_type IN ('character varying', 'character', 'text')) THEN
                     
            ALTER TABLE lab_results 
                ALTER COLUMN blood_sample_id TYPE bigint 
                USING (regexp_replace(blood_sample_id, '[^0-9]', '', 'g')::bigint);
        END IF;

        -- E. MIGRASI TABEL lab_results (PRIMARY KEY)
        IF EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name='lab_results' AND column_name='lab_result_id' 
                     AND data_type IN ('character varying', 'character', 'text')) THEN
                     
            ALTER TABLE lab_results 
                ALTER COLUMN lab_result_id TYPE bigint 
                USING (regexp_replace(lab_result_id, '[^0-9]', '', 'g')::bigint);

            ALTER TABLE lab_results 
                ALTER COLUMN lab_result_id ADD GENERATED BY DEFAULT AS IDENTITY;

            SELECT COALESCE(MAX(lab_result_id), 0) INTO v_max_id FROM lab_results;
            IF v_max_id > 0 THEN
                EXECUTE 'ALTER TABLE lab_results ALTER COLUMN lab_result_id RESTART WITH ' || (v_max_id + 1);
            END IF;
        END IF;

        -- F. BUAT ULANG FOREIGN KEY CONSTRAINT YANG TADI DIHAPUS
        ALTER TABLE lab_results 
            ADD CONSTRAINT fk_lab_results_blood_sample 
            FOREIGN KEY (blood_sample_id) 
            REFERENCES blood_samples(blood_sample_id);

    END IF;

    -- 3. TAMBAH KOLOM minute DI TABEL activities (JIKA BELUM ADA)
    -- Operasi ini diletakkan di luar blok 'v_need_migration' agar tetap berjalan mandiri
    -- di database lama maupun database baru hasil inisialisasi Hibernate.
    IF EXISTS (
        SELECT 1 FROM information_schema.tables 
        WHERE table_name = 'activities'
    ) THEN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns 
            WHERE table_name = 'activities' AND column_name = 'minute'
        ) THEN
            ALTER TABLE activities ADD COLUMN minute integer;
        END IF;
    END IF;

END $$;